export const DEFAULT_CACHE_PREFIX = 'firebase-mirror:';

export const RECEIVE_SNAPSHOTS = 'FIREBASE/RECEIVE_SNAPSHOTS';
export const UNSUBSCRIBE_FROM_VALUES = 'FIREBASE/UNSUBSCRIBE_FROM_VALUES';
export const SUBSCRIBE_TO_VALUES = 'FIREBASE/SUBSCRIBE_TO_VALUES';
